export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRIES_DETAIL = "GET_COUNTRIES_DETAIL";
export const SEARCH_BY_NAME = "SEARCH_BY_NAME";
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const CLEAR = "CLEAR";
//----------
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";
//----------
export const SORT_BY_ALPHABET = "SORT_BY_ALPHABET";
export const SORT_BY_POPULATION = "SORT_BY_POPULATION";